service: cinemap-user-api
provider:
  name: aws
  runtime: nodejs12.x
  region:  sa-east-1
  stage: dev
  memorySize: 128


functions:
  app:
    handler: app/app.handler
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true